# English (United States) translations for fb_vmware.
# Copyright (C) 2022 Frank Brehm, Berlin
# This file is distributed under the same license as the fb_vmware project.
# Frank Brehm <frank@brehm-online.com>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: fb_vmware 0.4.6\n"
"Report-Msgid-Bugs-To: frank@brehm-online.com\n"
"POT-Creation-Date: 2022-06-08 17:41+0200\n"
"PO-Revision-Date: 2022-06-08 17:25+0200\n"
"Last-Translator: Frank Brehm <frank@brehm-online.com>\n"
"Language: en_US\n"
"Language-Team: Frank Brehm <frank@brehm-online.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.1\n"

#: lib/fb_vmware/about.py:282 lib/fb_vmware/cluster.py:370 lib/fb_vmware/controller.py:266
#: lib/fb_vmware/datastore.py:225 lib/fb_vmware/dc.py:161 lib/fb_vmware/disk.py:388
#: lib/fb_vmware/ds_cluster.py:129 lib/fb_vmware/ether.py:501 lib/fb_vmware/host.py:249
#: lib/fb_vmware/host.py:673 lib/fb_vmware/host_port_group.py:198 lib/fb_vmware/network.py:140
#: lib/fb_vmware/vm.py:642
msgid "The given parameter {p!r} on calling method {m}() has failing attributes"
msgstr ""

#: lib/fb_vmware/about.py:290 lib/fb_vmware/cluster.py:281 lib/fb_vmware/dc.py:169
#: lib/fb_vmware/disk.py:397
msgid "Parameter {t!r} must be a {e} object, a {v} object was given instead."
msgstr ""

#: lib/fb_vmware/about.py:303 lib/fb_vmware/cluster.py:306 lib/fb_vmware/controller.py:308
#: lib/fb_vmware/datastore.py:265 lib/fb_vmware/dc.py:189 lib/fb_vmware/disk.py:419
#: lib/fb_vmware/ds_cluster.py:155 lib/fb_vmware/ether.py:466 lib/fb_vmware/host.py:281
#: lib/fb_vmware/host.py:591 lib/fb_vmware/host_port_group.py:222 lib/fb_vmware/network.py:172
#: lib/fb_vmware/vm.py:511
msgid "Creating {} object from:"
msgstr ""

#: lib/fb_vmware/about.py:339 lib/fb_vmware/controller.py:313 lib/fb_vmware/disk.py:424
#: lib/fb_vmware/ether.py:471 lib/fb_vmware/host_port_group.py:227 lib/fb_vmware/vm.py:592
msgid "Created {} object:"
msgstr ""

#: lib/fb_vmware/app/__init__.py:103
msgid "{what} of {app} .."
msgstr "{what} of {app} …"

#: lib/fb_vmware/app/__init__.py:106
msgid "Did not found any configured Vsphere environments."
msgstr ""

#: lib/fb_vmware/app/__init__.py:114
msgid "Checking for configured VSPhere instance {!r} ..."
msgstr "Checking for configured VSPhere instance {!r} …"

#: lib/fb_vmware/app/__init__.py:118
msgid "VSPhere {!r} not found in list of configured VSPhere instances."
msgstr ""

#: lib/fb_vmware/app/__init__.py:138
msgid "Enter password for {n} VSPhere user {u!r} on host {h!r}:"
msgstr ""

#: lib/fb_vmware/app/__init__.py:154
msgid "The VSPhere names from configuration, in which the VMs should be searched."
msgstr ""

#: lib/fb_vmware/app/__init__.py:162
msgid "Got command line arguments:"
msgstr ""

#: lib/fb_vmware/app/__init__.py:168
msgid "Initializing VSphere handlers ..."
msgstr "Initializing VSphere handlers …"

#: lib/fb_vmware/app/__init__.py:181
msgid "Initializing handler for VSPhere {!r} ..."
msgstr "Initializing handler for VSPhere {!r} …"

#: lib/fb_vmware/app/__init__.py:194
msgid "Could not initialize {} object from:"
msgstr ""

#: lib/fb_vmware/app/__init__.py:202
msgid "Cleaning up ..."
msgstr "Cleaning up …"

#: lib/fb_vmware/app/__init__.py:205
msgid "Closing VSPhere object {!r} ..."
msgstr "Closing VSPhere object {!r} …"

#: lib/fb_vmware/app/get_vm_info.py:56
msgid "Tries to get information about the given virtual machines in VMWare VSphere and print it out."
msgstr ""

#: lib/fb_vmware/app/get_vm_info.py:79
msgid "Names of the VM to get information."
msgstr ""

#: lib/fb_vmware/app/get_vm_info.py:93 lib/fb_vmware/app/get_vm_list.py:253
msgid "Starting {a!r}, version {v!r} ..."
msgstr "Starting {a!r}, version {v!r} …"

#: lib/fb_vmware/app/get_vm_info.py:148
msgid "NOT FOUND"
msgstr ""

#: lib/fb_vmware/app/get_vm_info.py:176 lib/fb_vmware/app/get_vm_info.py:192
#: lib/fb_vmware/app/get_vm_info.py:235
msgid "Unknown"
msgstr ""

#: lib/fb_vmware/app/get_vm_info.py:196
msgid "{nr:>2} disk "
msgid_plural "{nr:>2} disks"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/app/get_vm_info.py:212
msgid "Disk"
msgid_plural "Disks"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/app/get_vm_info.py:223
msgid "Total"
msgstr ""

#: lib/fb_vmware/app/get_vm_info.py:226 lib/fb_vmware/app/get_vm_info.py:242
msgid "None"
msgstr ""

#: lib/fb_vmware/app/get_vm_info.py:246
msgid "Custom Value"
msgid_plural "Custom Values"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/app/get_vm_list.py:60
msgid "Tries to get a list of all virtual machines in VMWare VSphere and print it out."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:141
msgid "Filter options"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:146
msgid "for names of VMs"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:147
msgid "A regular expression to filter the output list of VMs by their name (Default: {!r})."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:154
msgid "TYPE"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:155
msgid "Filter output for the type of the VM. Valid values are {li} (Default: {dflt!r})."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:164
msgid "Filter output for online VMs."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:168
msgid "Filter output for offline VMs and templates."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:173
msgid "for VMWare hardware config version"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:174
msgid ""
"A regular expression to filter the output list of VMs by the VMWare hardware configuration "
"version (e.g. '{}')."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:181
msgid "for the Operating System version"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:182
msgid ""
"A regular expression to filter the output list of VMs by their Operating System version, e.g. "
"'{}'."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:187
msgid "Output options"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:191
msgid "Detailed output list (quering data needs some time longer)."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:196
msgid ""
"The keys for sorting the output. Available keys are: {avail}. The default sorting keys are: "
"{default}."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:214
msgid "Regular expression for filtering: {!r}"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:217
msgid "Got a {c} for pattern {p!r}: {e}"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:224
msgid "Detailed output is required because of your given options."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:236
msgid "Sorting key {!r} not usable, if not detailed output was given."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:240
msgid "No usable sorting keys found, using default sorting keys {}."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:276
msgid "Using sorting keys:"
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:364
msgid "Found no VMWare VMs."
msgstr ""

#: lib/fb_vmware/app/get_vm_list.py:366
msgid "Found one VMWare VM."
msgid_plural "Found {} VMWare VMs."
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/app/get_vm_list.py:433
msgid "Found a {} object:"
msgstr ""

#: lib/fb_vmware/base.py:77
msgid "The given parameter {pc!r} ({pv!r}) is not a {o} object."
msgstr ""

#: lib/fb_vmware/base.py:82
msgid "No VSPhere host name or address given in {w}."
msgstr ""

#: lib/fb_vmware/base.py:86
msgid "The {c} object given as {w} is not initialized."
msgstr ""

#: lib/fb_vmware/base.py:186
msgid "Connecting to vSphere {!r} ..."
msgstr "Connecting to VSPhere {!r} …"

#: lib/fb_vmware/base.py:217
msgid "Disconnecting from VSPhere {!r}."
msgstr "Disconnecting from VSPhere {!r}."

#: lib/fb_vmware/cluster.py:263 lib/fb_vmware/controller.py:187 lib/fb_vmware/datastore.py:352
#: lib/fb_vmware/dc.py:127 lib/fb_vmware/disk.py:274 lib/fb_vmware/ds_cluster.py:194
#: lib/fb_vmware/ether.py:305 lib/fb_vmware/host.py:549 lib/fb_vmware/host_port_group.py:161
#: lib/fb_vmware/network.py:211 lib/fb_vmware/obj.py:273 lib/fb_vmware/vm.py:471
msgid "Comparing {} objects ..."
msgstr "Comparing {} objects …"

#: lib/fb_vmware/cluster.py:314
msgid "Cluster {c!r} has network {n!r}."
msgstr ""

#: lib/fb_vmware/cluster.py:321
msgid "Cluster {c!r} has datastore {d!r}."
msgstr ""

#: lib/fb_vmware/cluster.py:353 lib/fb_vmware/cluster.py:360
msgid "The given parameter {p!r} on calling method {m}() is not a sequence type."
msgstr ""

#: lib/fb_vmware/config/__init__.py:160
msgid "An empty name for a VSPhere datacenter is not allowed."
msgstr ""

#: lib/fb_vmware/config/__init__.py:174
msgid "An empty user name for connecting to a VSPhere datacenter is not allowed."
msgstr ""

#: lib/fb_vmware/config/__init__.py:283
msgid "Unknown key {k!r} with value {v!r} for VSphere {vs!r} in section {sec!r} found."
msgstr ""

#: lib/fb_vmware/config/__init__.py:289
msgid "{e} in section {sn!r} for VSphere {vs!r}:"
msgstr ""

#: lib/fb_vmware/config/__init__.py:295
msgid "There must be given at least the VSPhere hostname in section {sn!r} for VSphere {vs!r}."
msgstr ""

#: lib/fb_vmware/config/__init__.py:439
msgid "Evaluating config section {!r}:"
msgstr ""

#: lib/fb_vmware/config/__init__.py:448
msgid "Empty VSphere name found."
msgstr ""

#: lib/fb_vmware/connect.py:131
msgid "Trying to get some 'about' information from VSphere."
msgstr ""

#: lib/fb_vmware/connect.py:146
msgid "Got a {c} on requesting 'about' information from VSPhere {url}: {e}"
msgstr ""

#: lib/fb_vmware/connect.py:156
msgid "VSphere version: {!r}"
msgstr ""

#: lib/fb_vmware/connect.py:158
msgid "Found VSphere about-information:"
msgstr ""

#: lib/fb_vmware/connect.py:163
msgid "Trying to get datacenter from VSphere ..."
msgstr "Trying to get datacenter from VSphere …"

#: lib/fb_vmware/connect.py:177
msgid "Found VSphere datacenter {!r}."
msgstr ""

#: lib/fb_vmware/connect.py:179
msgid "Info about datacenter:"
msgstr ""

#: lib/fb_vmware/connect.py:190
msgid "Trying to get all clusters from VSphere ..."
msgstr "rying to get all clusters from VSphere …"

#: lib/fb_vmware/connect.py:214 lib/fb_vmware/connect.py:219
msgid "Found clusters:"
msgstr ""

#: lib/fb_vmware/connect.py:235 lib/fb_vmware/connect.py:494
msgid "Found standalone host"
msgstr ""

#: lib/fb_vmware/connect.py:237 lib/fb_vmware/connect.py:496
msgid "Found cluster"
msgstr ""

#: lib/fb_vmware/connect.py:238 lib/fb_vmware/connect.py:497
msgid "host"
msgid_plural "hosts"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:239 lib/fb_vmware/connect.py:498
msgid "CPU"
msgid_plural "CPUs"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:240 lib/fb_vmware/connect.py:499
msgid "thread"
msgid_plural "threads"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:241 lib/fb_vmware/connect.py:500
msgid "network"
msgid_plural "networks"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:242 lib/fb_vmware/connect.py:501
msgid "datastore"
msgid_plural "datastores"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:243 lib/fb_vmware/connect.py:502
msgid ""
"{on} {cl!r}, {h} {h_l}, {cpu} {cpu_l}, {thr} {t_l}, {mem:0.1f} GiB Memory, {net} {nw_l} and {ds}"
" {ds_l}."
msgstr ""

#: lib/fb_vmware/connect.py:266
msgid "Trying to get all datastores from VSphere ..."
msgstr "Trying to get all datastores from VSphere …"

#: lib/fb_vmware/connect.py:289 lib/fb_vmware/connect.py:291
msgid "Found datastores:"
msgstr ""

#: lib/fb_vmware/connect.py:299
msgid "Datastore mappings:"
msgstr ""

#: lib/fb_vmware/connect.py:314
msgid "Datastore {!r} seems to be local."
msgstr ""

#: lib/fb_vmware/connect.py:320
msgid "Found datastore {ds!r} of type {t!r}, capacity {c:0.1f} GByte."
msgstr ""

#: lib/fb_vmware/connect.py:329
msgid "Trying to get all datastore clusters from VSphere ..."
msgstr "Trying to get all datastore clusters from VSphere …"

#: lib/fb_vmware/connect.py:353 lib/fb_vmware/connect.py:356
msgid "Found datastore clusters:"
msgstr ""

#: lib/fb_vmware/connect.py:358
msgid "No VSphere datastore clusters found."
msgstr ""

#: lib/fb_vmware/connect.py:364
msgid "Datastore cluster mappings:"
msgstr ""

#: lib/fb_vmware/connect.py:370 lib/fb_vmware/connect.py:430
msgid "Found a {} child."
msgstr ""

#: lib/fb_vmware/connect.py:388
msgid "Trying to get all networks from VSphere ..."
msgstr "Trying to get all networks from VSphere …"

#: lib/fb_vmware/connect.py:410
msgid "Found one VSphere network."
msgid_plural "Found {n} VSphere networks."
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:414 lib/fb_vmware/connect.py:416
msgid "Found VSphere networks:"
msgstr ""

#: lib/fb_vmware/connect.py:418
msgid "No VSphere networks found."
msgstr ""

#: lib/fb_vmware/connect.py:424
msgid "Network mappings:"
msgstr ""

#: lib/fb_vmware/connect.py:448
msgid "Trying to get all host systems from VSphere ..."
msgstr "Trying to get all host systems from VSphere …"

#: lib/fb_vmware/connect.py:475 lib/fb_vmware/connect.py:480
msgid "Found hosts:"
msgstr ""

#: lib/fb_vmware/connect.py:486
msgid "Checking {o}-object in cluster {c!r} ..."
msgstr "Checking {o}-object in cluster {c!r} …"

#: lib/fb_vmware/connect.py:513
msgid "Found host {h!r} in cluster {c!r}."
msgstr ""

#: lib/fb_vmware/connect.py:528
msgid "Searching for VM {n!r} (pattern: {p!r}) in VSPhere {v!r} ..."
msgstr "Searching for VM {n!r} (pattern: {p!r}) in VSPhere {v!r} …"

#: lib/fb_vmware/connect.py:536
msgid "VSphere VM {!r} not found."
msgstr ""

#: lib/fb_vmware/connect.py:549 lib/fb_vmware/datastore.py:234 lib/fb_vmware/ds_cluster.py:138
#: lib/fb_vmware/iface.py:58 lib/fb_vmware/network.py:148
msgid "Parameter {t!r} must be a {e}, {v!r} was given."
msgstr ""

#: lib/fb_vmware/connect.py:638
msgid "Parameter {p!r} => {r!r} seems not to be a regex object."
msgstr ""

#: lib/fb_vmware/connect.py:642
msgid "Parameter {p1!r} and {p2!r} may not be {w!r} at the same time."
msgstr ""

#: lib/fb_vmware/connect.py:646
msgid "Trying to get list of VMs with name pattern {!r} ..."
msgstr "Trying to get list of VMs with name pattern {!r} …"

#: lib/fb_vmware/connect.py:666
msgid "Searching in path {!r} ..."
msgstr "Searching in path {!r} …"

#: lib/fb_vmware/connect.py:679
msgid "Found one VM with pattern {p!r}."
msgid_plural "Found {no} VMs with pattern {p!r}."
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:714
msgid "Checking VM {!r} ..."
msgstr "Checking VM {!r} …"

#: lib/fb_vmware/connect.py:717
msgid "Checking VM {!r} for being a template ..."
msgstr "Checking VM {!r} for being a template …"

#: lib/fb_vmware/connect.py:719
msgid "Checking VM {!r} for being not a template ..."
msgstr "Checking VM {!r} for being not a template …"

#: lib/fb_vmware/connect.py:727
msgid "Checking VM {!r} for pattern."
msgstr ""

#: lib/fb_vmware/connect.py:730
msgid "Found VM {!r}."
msgstr ""

#: lib/fb_vmware/connect.py:794
msgid "VM {!r} is already powered on."
msgstr ""

#: lib/fb_vmware/connect.py:797
msgid "Powering on VM {!r} ..."
msgstr "Powering on VM {!r} …"

#: lib/fb_vmware/connect.py:801
msgid "VM {!r} successful powered on."
msgstr ""

#: lib/fb_vmware/connect.py:825
msgid "VM {!r} is already powered off."
msgstr ""

#: lib/fb_vmware/connect.py:828
msgid "Powering off VM {!r} ..."
msgstr "Powering off VM {!r} …"

#: lib/fb_vmware/connect.py:832
msgid "VM {!r} successful powered off."
msgstr ""

#: lib/fb_vmware/connect.py:840
msgid "Ensuring existence of VSphere VM folders:"
msgstr ""

#: lib/fb_vmware/connect.py:857
msgid "Trying to get VM folder object for path {!r}."
msgstr ""

#: lib/fb_vmware/connect.py:882
msgid "Checking single VM folder {i}: {f!r}."
msgstr ""

#: lib/fb_vmware/connect.py:893
msgid "Found VM folder {n}, parent: {p}"
msgstr ""

#: lib/fb_vmware/connect.py:911
msgid "Ensuring existence of VSphere VM folder {!r}."
msgstr ""

#: lib/fb_vmware/connect.py:936
msgid "VM Folder {!r} already exists."
msgstr ""

#: lib/fb_vmware/connect.py:938
msgid "Creating VM folder {!r} ..."
msgstr "Creating VM folder {!r} …"

#: lib/fb_vmware/connect.py:940
msgid "Simulation mode, don't creating it."
msgstr ""

#: lib/fb_vmware/connect.py:956
msgid "Waiting for tasks to finish ..."
msgstr "Waiting for tasks to finish …"

#: lib/fb_vmware/connect.py:968
msgid "Waiting at most {m} seconds for tasks {t} to finish ..."
msgstr "Waiting at most {m} seconds for tasks {t} to finish …"

#: lib/fb_vmware/connect.py:971
msgid "Waiting for tasks {} to finish ..."
msgstr "Waiting for tasks {} to finish …"

#: lib/fb_vmware/connect.py:991
msgid "Waiting ..."
msgstr "Waiting …"

#: lib/fb_vmware/connect.py:1025
msgid "Creating VM {!r} ..."
msgstr "Creating VM {!r} …"

#: lib/fb_vmware/connect.py:1028
msgid "Simulation mode - VM {!r} will not be created."
msgstr ""

#: lib/fb_vmware/connect.py:1046
msgid "Generating create spec for VM {!r} ..."
msgstr "Generating create spec for VM {!r} …"

#: lib/fb_vmware/connect.py:1054
msgid "Datastore path: {!r}"
msgstr ""

#: lib/fb_vmware/connect.py:1057
msgid "VM path name: {!r}"
msgstr ""

#: lib/fb_vmware/connect.py:1107
msgid "Generated VM config:"
msgstr ""

#: lib/fb_vmware/connect.py:1116
msgid "Given disksize {!r} must be greater than zero."
msgstr ""

#: lib/fb_vmware/connect.py:1129
msgid "There may be created at most 6 disks, but {} were given."
msgstr ""

#: lib/fb_vmware/connect.py:1143
msgid "Generating spec for SCSI controller and one disk: {d}"
msgid_plural "Generating spec for SCSI controller and {n} disks: {d}"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/connect.py:1146
msgid "Generating spec for SCSI controller without disks."
msgstr ""

#: lib/fb_vmware/connect.py:1171
msgid "Adding spec for disk {n!r} with {gb} GiB => {kb} KiByte."
msgstr ""

#: lib/fb_vmware/connect.py:1206
msgid "Invalid Interface description {!r} given."
msgstr ""

#: lib/fb_vmware/connect.py:1217
msgid "Defined interface:"
msgstr ""

#: lib/fb_vmware/connect.py:1221
msgid "Adding spec for network interface {d!r} (Network {n!r}, MAC: {m!r}, summary: {s!r})."
msgstr ""

#: lib/fb_vmware/connect.py:1273
msgid "Purging VM {!r} ..."
msgstr "Purging VM {!r} …"

#: lib/fb_vmware/connect.py:1277
msgid "VM {!r} successful removed."
msgstr ""

#: lib/fb_vmware/connect.py:1308
msgid "Did not found virtual ethernet device No. {no} (found {count} devices)."
msgstr ""

#: lib/fb_vmware/connect.py:1327
msgid "Changes of MAC address:"
msgstr ""

#: lib/fb_vmware/connect.py:1331
msgid "Successful changed MAC address of VM {v!r} to {m!r}."
msgstr ""

#: lib/fb_vmware/connect.py:1344
msgid "Trying to detect all field names of custom field definitions."
msgstr ""

#: lib/fb_vmware/connect.py:1361
msgid "Got a {c} on requesting custom field names from VSPhere {url}: {e}"
msgstr "Got a {c} on requesting custom field names from VSPhere {url}: {e}"

#: lib/fb_vmware/connect.py:1367
msgid "Got custom field names from VSPhere {}:"
msgstr ""

#: lib/fb_vmware/controller.py:56
msgid "Virtual IDE controller"
msgstr ""

#: lib/fb_vmware/controller.py:57
msgid "Virtual VNME controller"
msgstr ""

#: lib/fb_vmware/controller.py:58
msgid "Virtual PCI controller"
msgstr ""

#: lib/fb_vmware/controller.py:59
msgid "Virtual controller for keyboards and mice"
msgstr ""

#: lib/fb_vmware/controller.py:60
msgid "Virtual AHCI SATA controller"
msgstr ""

#: lib/fb_vmware/controller.py:61
msgid "Virtual SATA controller"
msgstr ""

#: lib/fb_vmware/controller.py:62
msgid "Virtual paravirtualized SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:63
msgid "Virtual BusLogic SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:64
msgid "Virtual LSI SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:65
msgid "Virtual LSI Logic SAS SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:66
msgid "Virtual SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:67
msgid "Virtual Super IO Controller for floppy drives, parallel ports, and serial ports"
msgstr ""

#: lib/fb_vmware/controller.py:69
msgid "Virtual USB controller (USB 1.1 and 2.0)"
msgstr ""

#: lib/fb_vmware/controller.py:70
msgid "Virtual USB Extensible Host Controller Interface (USB 3.0)"
msgstr ""

#: lib/fb_vmware/controller.py:71
msgid "Unknown virtual controller"
msgstr ""

#: lib/fb_vmware/controller.py:275 lib/fb_vmware/ether.py:415 lib/fb_vmware/host.py:257
#: lib/fb_vmware/host.py:571 lib/fb_vmware/host_port_group.py:206 lib/fb_vmware/vm.py:495
msgid "Parameter {t!r} must be a {e}, {v!r} ({vt}) was given."
msgstr ""

#: lib/fb_vmware/controller.py:297
msgid "Checking class of controller: {!r}"
msgstr ""

#: lib/fb_vmware/controller.py:324 lib/fb_vmware/disk.py:435 lib/fb_vmware/ether.py:514
#: lib/fb_vmware/host_port_group.py:238 lib/fb_vmware/vm.py:655
msgid "Invalid type {t!r} as an item of a {c}, only {o} objects are allowed."
msgstr ""

#: lib/fb_vmware/controller.py:392 lib/fb_vmware/disk.py:503 lib/fb_vmware/ether.py:582
#: lib/fb_vmware/host.py:798 lib/fb_vmware/host_port_group.py:327 lib/fb_vmware/vm.py:723
msgid "{m} takes at most {max} arguments ({n} given)."
msgstr ""

#: lib/fb_vmware/controller.py:431
msgid "Controller is not in controller list."
msgstr ""

#: lib/fb_vmware/datastore.py:370 lib/fb_vmware/ds_cluster.py:212 lib/fb_vmware/network.py:229
msgid "Invalid item type {{!r}} to set, only {} allowed."
msgstr ""

#: lib/fb_vmware/datastore.py:372
msgid "The key {k!r} must be equal to the datastore name {n!r}."
msgstr ""

#: lib/fb_vmware/datastore.py:373 lib/fb_vmware/ds_cluster.py:215 lib/fb_vmware/network.py:232
msgid "None type as key is not allowed."
msgstr ""

#: lib/fb_vmware/datastore.py:374 lib/fb_vmware/ds_cluster.py:216 lib/fb_vmware/network.py:233
msgid "Empty key {!r} is not allowed."
msgstr ""

#: lib/fb_vmware/datastore.py:375 lib/fb_vmware/ds_cluster.py:217 lib/fb_vmware/network.py:234
#: lib/fb_vmware/obj.py:255 lib/fb_vmware/obj.py:264 lib/fb_vmware/obj.py:284 lib/fb_vmware/obj.py:296
msgid "Object {{!r}} is not a {} object."
msgstr ""

#: lib/fb_vmware/datastore.py:607
msgid "Could not handle datastore type {!r}."
msgstr ""

#: lib/fb_vmware/datastore.py:614
msgid "Could not found a datastore for {c:0.1f} GiB of type {t!r}."
msgstr ""

#: lib/fb_vmware/datastore.py:621
msgid "Searching datastore for {c:0.1f} GiB of type {t!r}."
msgstr ""

#: lib/fb_vmware/disk.py:543
msgid "Disk is not in disk list."
msgstr ""

#: lib/fb_vmware/ds_cluster.py:214
msgid "The key {k!r} must be equal to the datastore cluster name {n!r}."
msgstr ""

#: lib/fb_vmware/errors.py:50
msgid "No VSphere datastores found."
msgstr ""

#: lib/fb_vmware/errors.py:80
msgid "Invalid name {n!r} for a {o} VSphere object."
msgstr ""

#: lib/fb_vmware/errors.py:83
msgid "Invalid name {!r} for a VSphere object."
msgstr ""

#: lib/fb_vmware/errors.py:101
msgid "The VSphere datacenter {!r} is not existing."
msgstr ""

#: lib/fb_vmware/errors.py:117
msgid "The VSphere Virtual machine {!r} was not found."
msgstr ""

#: lib/fb_vmware/errors.py:137
msgid "No SAN based datastore found with at least {m:0.0f} MiB == {g:0.1f} GiB available space found."
msgstr ""

#: lib/fb_vmware/errors.py:155
msgid "The network {!r} is not existing."
msgstr ""

#: lib/fb_vmware/errors.py:172
msgid "Could not connect to the vSphere {!r}."
msgstr ""

#: lib/fb_vmware/errors.py:189
msgid "Got a {c} on connecting to vSphere {url!r}:"
msgstr "Got a {c} on connecting to vSphere {url!r}:"

#: lib/fb_vmware/errors.py:212
msgid "Timeout on creating VM {vm!r} after {to:0.1f} seconds."
msgstr ""

#: lib/fb_vmware/errors.py:215
msgid "Timeout on creating VM {!r}."
msgstr ""

#: lib/fb_vmware/errors.py:231
msgid "Invalid type of {!r} for a port of a VSPhere server"
msgstr ""

#: lib/fb_vmware/errors.py:255
msgid ""
"Invalid port number {port!r} for the VSphere server, PORT must be greater than zero and less or "
"equal to {max}."
msgstr ""

#: lib/fb_vmware/ether.py:443
msgid "Checking class of ethernet card: {!r}"
msgstr ""

#: lib/fb_vmware/ether.py:621
msgid "card is not in card list."
msgstr ""

#: lib/fb_vmware/host.py:348 lib/fb_vmware/vm.py:111
msgid "The name of the vsphere may not be empty."
msgstr ""

#: lib/fb_vmware/host.py:576
msgid "Host {!r} seems to be offline!"
msgstr ""

#: lib/fb_vmware/host.py:728
msgid "Invalid type {{t!r}} as an item of a {{c}}, only {} objects are allowed."
msgstr ""

#: lib/fb_vmware/host.py:837
msgid "host is not in host list."
msgstr ""

#: lib/fb_vmware/host_port_group.py:366
msgid "group is not in group list."
msgstr ""

#: lib/fb_vmware/iface.py:126
msgid "Invalid MAC address {!r} for interface given."
msgstr ""

#: lib/fb_vmware/network.py:71
msgid "Trying to get IPv4 network {n!r} -> {i!r}."
msgstr ""

#: lib/fb_vmware/network.py:78
msgid "Could not get IP network from network name {!r}."
msgstr ""

#: lib/fb_vmware/network.py:81
msgid "Network {!r} has no IP network assigned."
msgstr ""

#: lib/fb_vmware/network.py:87
msgid "Initialized network object:"
msgstr ""

#: lib/fb_vmware/network.py:231
msgid "The key {k!r} must be equal to the network name {n!r}."
msgstr ""

#: lib/fb_vmware/network.py:479
msgid "Searching VSphere network for address {} ..."
msgstr "Searching VSphere network for address {} …"

#: lib/fb_vmware/network.py:485
msgid "Found network {n!r} for IP {i}."
msgstr ""

#: lib/fb_vmware/network.py:489
msgid "Could not find VSphere network for IP {}."
msgstr ""

#: lib/fb_vmware/network.py:492
msgid "Could not find VSphere network for IP addresses {}."
msgstr ""

#: lib/fb_vmware/obj.py:78
msgid "The type of a {} may not be None."
msgstr ""

#: lib/fb_vmware/obj.py:83 lib/fb_vmware/obj.py:106 lib/fb_vmware/obj.py:129
msgid "Invalid {w}.{p} {v!r}."
msgstr ""

#: lib/fb_vmware/obj.py:145
msgid "The name prefix of a {} may not be None."
msgstr ""

#: lib/fb_vmware/obj.py:149
msgid "Invalid name prefix {p!r} for a {o}."
msgstr ""

#: lib/fb_vmware/vm.py:584
msgid "Unknown hardware device of type {}."
msgstr ""

#: lib/fb_vmware/vm.py:587
msgid "There is something wrong wit VM {n!r} in cluster {c!r} and path {p!r} ..."
msgstr "There is something wrong with VM {n!r} in cluster {c!r} and path {p!r} …"

#: lib/fb_vmware/vm.py:762
msgid "VM is not in VM list."
msgstr ""

#: lib/fb_vmware/xlate.py:98
msgid "Module directory:"
msgstr ""

#: lib/fb_vmware/xlate.py:99
msgid "Base directory:"
msgstr ""

#: lib/fb_vmware/xlate.py:100
msgid "Locale directory:"
msgstr ""

#: lib/fb_vmware/xlate.py:101
msgid "Locale domain:"
msgstr ""

#: lib/fb_vmware/xlate.py:102
msgid "Found .mo-file:"
msgstr ""

